name: pocket_coach
description: "Your personal AI pocket coach."
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI / Design
  google_fonts: ^6.2.1
  gap: ^3.0.1
  flutter_animate: ^4.5.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # Utils
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  equatable: ^2.0.5
  dart_openai: ^6.1.1
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^6.1.0
  purchases_flutter: ^9.10.7
  purchases_ui_flutter: ^9.10.7
  firebase_core: ^4.4.0
  firebase_analytics: ^12.1.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/coaches.json
    - assets/coaches/
    - .env
